import { Program, Statement, WhereClause, Condition } from "./types";

export function generateTypeScript(program: Program): string {
  const lines: string[] = [
    "// Generated by FORAX Phase 3 deterministic compiler.",
    "// Do not edit generated code; edit the .forax source instead.",
    'import { forensicRuntime } from "../runtime/forensicRuntime";',
    "",
    "export async function main(): Promise<void> {"
  ];

  for (const statement of program.statements) {
    for (const line of generateStatement(statement)) {
      lines.push(`  ${line}`);
    }
  }

  lines.push(
    "}",
    "",
    "main().catch((error) => {",
    "  console.error(error);",
    "  process.exitCode = 1;",
    "});",
    ""
  );

  return lines.join("\n");
}

function generateStatement(statement: Statement): string[] {
  switch (statement.type) {
    case "CaseStatement":
      return [`await forensicRuntime.openCase(${JSON.stringify(statement.id)});`];

    case "LoadPcapStatement":
      return [`await forensicRuntime.loadPcap(${JSON.stringify(statement.path)});`];

    case "CollectStatement":
      return [`await forensicRuntime.collect(${JSON.stringify(statement.object)});`];

    case "FindStatement":
      return [
        `await forensicRuntime.find(${JSON.stringify(statement.object)}, ${whereArg(statement.where)});`
      ];

    case "CountStatement":
      return [
        `await forensicRuntime.count(${JSON.stringify(statement.object)}, ${whereArg(statement.where)});`
      ];
    case "FilterStatement":
      return [
        `await forensicRuntime.filter(${JSON.stringify(statement.object)}, ${whereArg(statement.where)});`
      ];

    case "CorrelateStatement":
      return [
        "await forensicRuntime.correlateProcessNetwork();"
      ];
    case "SummarizeProcessStatement":
      return [
        "await forensicRuntime.summarizeProcess();"
      ];

    case "CreateTimelineStatement":
      return ["await forensicRuntime.createTimeline();"];

    case "ReportStatement":
      return ["await forensicRuntime.report();"];

    case "StartNetworkMonitorStatement":
      return ["await forensicRuntime.startNetworkMonitor();"];

    case "StopNetworkMonitorStatement":
      return ["await forensicRuntime.stopNetworkMonitor();"];

      case "MonitorNetworkStatement":
        if (statement.object === "PROCESS") {
          return [
            `await forensicRuntime.monitorProcess(${statement.durationSeconds});`
          ];
        }

        return [
          `await forensicRuntime.monitorNetwork(${JSON.stringify(statement.object)}, ${statement.durationSeconds});`
        ];
    case "WatchStatement":
      return [
        `await forensicRuntime.watch(${JSON.stringify(statement.object)});`
      ];

    case "HashFileStatement":
      return [
        `await forensicRuntime.hashFile(${JSON.stringify(statement.path)});`
      ];

    case "VerifyFileStatement":
      return [
        `await forensicRuntime.verifyFile(${JSON.stringify(statement.path)}, ${JSON.stringify(statement.expectedHash)});`
      ];

    case "GetProcessStatement":
      return [
        `await forensicRuntime.getProcess(${statement.pid});`
      ];
      case "SearchFileStatement":
        return [
          `await forensicRuntime.searchFile(${JSON.stringify(statement.directory)}, ${JSON.stringify(statement.pattern)});`
        ];

    case "GetFileStatement":
      return [
        `await forensicRuntime.getFile(${JSON.stringify(statement.path)});`
      ];

    default:
      return [];
  }
}
function whereArg(where?: WhereClause): string {
  if (!where) {
    return "undefined";
  }

  return JSON.stringify({
    conditions: where.conditions.map((condition: Condition) => ({
      field: condition.field,
      operator: condition.operator,
      value: condition.value
    })),
    operators: where.operators
  });
}







